In [24]:
# pip install transformers
import tensorflow as tf

In [10]:
import warnings
warnings.filterwarnings("ignore")

In [28]:
from transformers import pipeline
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
classifier = pipeline('sentiment-analysis')

In [12]:
txt_1 = 'Jupyter Notebook is one of the best tools for machine learning!'
classifier(txt_1)

[{'label': 'POSITIVE', 'score': 0.9997950196266174}]

In [14]:
txt_2 = 'The weather is unpredictable around here'
classifier(txt_2)

[{'label': 'POSITIVE', 'score': 0.6950820088386536}]

In [29]:
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_139']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [18]:
inputs = tokenizer([txt_1, txt_2])

In [19]:
inputs

{'input_ids': [[101, 18414, 7685, 3334, 14960, 2003, 2028, 1997, 1996, 2190, 5906, 2005, 3698, 4083, 999, 102], [101, 1996, 4633, 2003, 21446, 2105, 2182, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]}

In [20]:
inputs_with_padding = tokenizer([txt_1, txt_2], padding = True, truncation = True, max_length = 256, return_tensors="tf")

In [21]:
inputs_with_padding

{'input_ids': <tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[  101, 18414,  7685,  3334, 14960,  2003,  2028,  1997,  1996,
         2190,  5906,  2005,  3698,  4083,   999,   102],
       [  101,  1996,  4633,  2003, 21446,  2105,  2182,   102,     0,
            0,     0,     0,     0,     0,     0,     0]])>, 'attention_mask': <tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])>}

In [22]:
outputs = model(inputs_with_padding)

In [23]:
outputs

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-4.1002707 ,  4.391923  ],
       [-0.33054978,  0.49343714]], dtype=float32)>, hidden_states=None, attentions=None)

In [25]:
predictions = tf.nn.softmax(outputs[0], axis=-1)

In [26]:
predictions

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.0502099e-04, 9.9979502e-01],
       [3.0491802e-01, 6.9508201e-01]], dtype=float32)>